### ISSUE TITLE

        feat!: vite dev default port is now 5173
    

### ISSUE THREAD

**Issue by mrcego** [mrcego/vite-spanish-docs-translation#106]
New updates on head repo.
https://github.com/vitejs/vite/commit/1cc2e2d2d5db55fd54f4e0cc8f3dbc1176706ea6

**Comment by StephHoel** [comment]
How can I change this port?

**Comment by mrcego** [comment]
> How can I change this port?

https://es.vitejs.dev/config/server-options.html#server-port
